name: Vesper Sport
title: Vesper Sport
email: info@vespersport.com
description: Kitesurf and wakeboards handcrafted in Poland from European materials.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://vespersport.com # the base hostname & protocol for your site
twitter_username:
github_username:
facebook: vespersport
instagram: vesper_sport
youtube:

# Build settings
markdown: kramdown
highlighter: null
exclude: ["node_modules", "gulpfile.js", "package.json"]
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
